// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// AuthRoutes is an autogenerated mock type for the AuthRoutes type
type AuthRoutes struct {
	mock.Mock
}

// AuthMobile provides a mock function with given fields: apiGroup
func (_m *AuthRoutes) AuthMobile(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// AuthWeb provides a mock function with given fields: apiGroup
func (_m *AuthRoutes) AuthWeb(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// NewAuthRoutes creates a new instance of AuthRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRoutes {
	mock := &AuthRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
