// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/HarsaEdu/harsa-api/internal/model/domain"
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"

	web "github.com/HarsaEdu/harsa-api/internal/model/web"
)

// CategoryService is an autogenerated mock type for the CategoryService type
type CategoryService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, category
func (_m *CategoryService) Create(ctx echo.Context, category web.CategoryCreateRequest) error {
	ret := _m.Called(ctx, category)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, web.CategoryCreateRequest) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *CategoryService) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindById provides a mock function with given fields: id
func (_m *CategoryService) FindById(id int) (*domain.Category, error) {
	ret := _m.Called(id)

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Category, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Category); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: offset, limit, search
func (_m *CategoryService) GetAll(offset int, limit int, search string) ([]domain.Category, *web.Pagination, error) {
	ret := _m.Called(offset, limit, search)

	var r0 []domain.Category
	var r1 *web.Pagination
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]domain.Category, *web.Pagination, error)); ok {
		return rf(offset, limit, search)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []domain.Category); ok {
		r0 = rf(offset, limit, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) *web.Pagination); ok {
		r1 = rf(offset, limit, search)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*web.Pagination)
		}
	}

	if rf, ok := ret.Get(2).(func(int, int, string) error); ok {
		r2 = rf(offset, limit, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, request, id, isImageExist
func (_m *CategoryService) Update(ctx echo.Context, request web.CategoryUpdateRequest, id int, isImageExist bool) error {
	ret := _m.Called(ctx, request, id, isImageExist)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, web.CategoryUpdateRequest, int, bool) error); ok {
		r0 = rf(ctx, request, id, isImageExist)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadImage provides a mock function with given fields: ctx, request, id, isIconExist, isImageExist
func (_m *CategoryService) UploadImage(ctx echo.Context, request *web.CategoryUploadImageRequest, id int, isIconExist bool, isImageExist bool) error {
	ret := _m.Called(ctx, request, id, isIconExist, isImageExist)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, *web.CategoryUploadImageRequest, int, bool, bool) error); ok {
		r0 = rf(ctx, request, id, isIconExist, isImageExist)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCategoryService creates a new instance of CategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryService {
	mock := &CategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
