// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// FaqsRoutes is an autogenerated mock type for the FaqsRoutes type
type FaqsRoutes struct {
	mock.Mock
}

// FaqsMobile provides a mock function with given fields: apiGroup
func (_m *FaqsRoutes) FaqsMobile(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// FaqsWeb provides a mock function with given fields: apiGroup
func (_m *FaqsRoutes) FaqsWeb(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// NewFaqsRoutes creates a new instance of FaqsRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFaqsRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *FaqsRoutes {
	mock := &FaqsRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
