// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/HarsaEdu/harsa-api/internal/model/domain"
	mock "github.com/stretchr/testify/mock"

	web "github.com/HarsaEdu/harsa-api/internal/model/web"
)

// FaqsService is an autogenerated mock type for the FaqsService type
type FaqsService struct {
	mock.Mock
}

// Create provides a mock function with given fields: faqs
func (_m *FaqsService) Create(faqs web.FaqsRequest) error {
	ret := _m.Called(faqs)

	var r0 error
	if rf, ok := ret.Get(0).(func(web.FaqsRequest) error); ok {
		r0 = rf(faqs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *FaqsService) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: offset, limit, search
func (_m *FaqsService) GetAll(offset int, limit int, search string) ([]domain.Faqs, *web.Pagination, error) {
	ret := _m.Called(offset, limit, search)

	var r0 []domain.Faqs
	var r1 *web.Pagination
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]domain.Faqs, *web.Pagination, error)); ok {
		return rf(offset, limit, search)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []domain.Faqs); ok {
		r0 = rf(offset, limit, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Faqs)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) *web.Pagination); ok {
		r1 = rf(offset, limit, search)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*web.Pagination)
		}
	}

	if rf, ok := ret.Get(2).(func(int, int, string) error); ok {
		r2 = rf(offset, limit, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetById provides a mock function with given fields: id
func (_m *FaqsService) GetById(id int) (*domain.Faqs, error) {
	ret := _m.Called(id)

	var r0 *domain.Faqs
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Faqs, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Faqs); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Faqs)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: faqs, id
func (_m *FaqsService) Update(faqs web.FaqsUpdateRequest, id int) error {
	ret := _m.Called(faqs, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(web.FaqsUpdateRequest, int) error); ok {
		r0 = rf(faqs, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFaqsService creates a new instance of FaqsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFaqsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FaqsService {
	mock := &FaqsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
