// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// FeedbackRoutes is an autogenerated mock type for the FeedbackRoutes type
type FeedbackRoutes struct {
	mock.Mock
}

// FeedbackMobile provides a mock function with given fields: apiGroup
func (_m *FeedbackRoutes) FeedbackMobile(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// FeedbackWeb provides a mock function with given fields: apiGroup
func (_m *FeedbackRoutes) FeedbackWeb(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// NewFeedbackRoutes creates a new instance of FeedbackRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFeedbackRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *FeedbackRoutes {
	mock := &FeedbackRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
