// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	web "github.com/HarsaEdu/harsa-api/internal/model/web"
	mock "github.com/stretchr/testify/mock"
)

// Firebase is an autogenerated mock type for the Firebase type
type Firebase struct {
	mock.Mock
}

// SendNotificationMulticast provides a mock function with given fields: notif
func (_m *Firebase) SendNotificationMulticast(notif *web.NotificationMultiCast) {
	_m.Called(notif)
}

// SendNotificationPersonal provides a mock function with given fields: notif
func (_m *Firebase) SendNotificationPersonal(notif *web.NotificationPersonal) {
	_m.Called(notif)
}

// NewFirebase creates a new instance of Firebase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFirebase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Firebase {
	mock := &Firebase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
