// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// HistorySubModuleRoutes is an autogenerated mock type for the HistorySubModuleRoutes type
type HistorySubModuleRoutes struct {
	mock.Mock
}

// MobileHistorySubModule provides a mock function with given fields: apiGroup
func (_m *HistorySubModuleRoutes) MobileHistorySubModule(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// NewHistorySubModuleRoutes creates a new instance of HistorySubModuleRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHistorySubModuleRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *HistorySubModuleRoutes {
	mock := &HistorySubModuleRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
