// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// InterestHandler is an autogenerated mock type for the InterestHandler type
type InterestHandler struct {
	mock.Mock
}

// CreateInterest provides a mock function with given fields: ctx
func (_m *InterestHandler) CreateInterest(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetInterestRecommendation provides a mock function with given fields: ctx
func (_m *InterestHandler) GetInterestRecommendation(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInterestHandler creates a new instance of InterestHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterestHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *InterestHandler {
	mock := &InterestHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
