// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// InterestRoutes is an autogenerated mock type for the InterestRoutes type
type InterestRoutes struct {
	mock.Mock
}

// MobileInterest provides a mock function with given fields: apiGroup
func (_m *InterestRoutes) MobileInterest(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// WebInterest provides a mock function with given fields: apiGroup
func (_m *InterestRoutes) WebInterest(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// NewInterestRoutes creates a new instance of InterestRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterestRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *InterestRoutes {
	mock := &InterestRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
