// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// NotificationRoutes is an autogenerated mock type for the NotificationRoutes type
type NotificationRoutes struct {
	mock.Mock
}

// NotificationMobile provides a mock function with given fields: apiGroup
func (_m *NotificationRoutes) NotificationMobile(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// NotificationWeb provides a mock function with given fields: apiGroup
func (_m *NotificationRoutes) NotificationWeb(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// NewNotificationRoutes creates a new instance of NotificationRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRoutes {
	mock := &NotificationRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
