// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/HarsaEdu/harsa-api/internal/model/domain"
	mock "github.com/stretchr/testify/mock"

	web "github.com/HarsaEdu/harsa-api/internal/model/web"
)

// NotificationRepository is an autogenerated mock type for the NotificationRepository type
type NotificationRepository struct {
	mock.Mock
}

// ArsipNotification provides a mock function with given fields: arsip
func (_m *NotificationRepository) ArsipNotification(arsip web.ArsipNotification) error {
	ret := _m.Called(arsip)

	var r0 error
	if rf, ok := ret.Get(0).(func(web.ArsipNotification) error); ok {
		r0 = rf(arsip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: Notification
func (_m *NotificationRepository) Create(Notification *domain.Notification) error {
	ret := _m.Called(Notification)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Notification) error); ok {
		r0 = rf(Notification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *NotificationRepository) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindById provides a mock function with given fields: id
func (_m *NotificationRepository) FindById(id int) (*domain.Notification, error) {
	ret := _m.Called(id)

	var r0 *domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Notification, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Notification); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: offset, limit, userID
func (_m *NotificationRepository) GetAll(offset int, limit int, userID uint) ([]domain.Notification, int64, error) {
	ret := _m.Called(offset, limit, userID)

	var r0 []domain.Notification
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, uint) ([]domain.Notification, int64, error)); ok {
		return rf(offset, limit, userID)
	}
	if rf, ok := ret.Get(0).(func(int, int, uint) []domain.Notification); ok {
		r0 = rf(offset, limit, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, uint) int64); ok {
		r1 = rf(offset, limit, userID)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, uint) error); ok {
		r2 = rf(offset, limit, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ReadNotification provides a mock function with given fields: id
func (_m *NotificationRepository) ReadNotification(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationRepository creates a new instance of NotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepository {
	mock := &NotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
