// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ProfileRoutes is an autogenerated mock type for the ProfileRoutes type
type ProfileRoutes struct {
	mock.Mock
}

// ProfileMobile provides a mock function with given fields: apiGroup
func (_m *ProfileRoutes) ProfileMobile(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// ProfileWeb provides a mock function with given fields: apiGroup
func (_m *ProfileRoutes) ProfileWeb(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// NewProfileRoutes creates a new instance of ProfileRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileRoutes {
	mock := &ProfileRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
