// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// QuestionsHandler is an autogenerated mock type for the QuestionsHandler type
type QuestionsHandler struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx
func (_m *QuestionsHandler) Delete(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQuestionsHandler creates a new instance of QuestionsHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuestionsHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuestionsHandler {
	mock := &QuestionsHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
