// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// QuizzesRoutes is an autogenerated mock type for the QuizzesRoutes type
type QuizzesRoutes struct {
	mock.Mock
}

// QuizzesMobile provides a mock function with given fields: apiGroup
func (_m *QuizzesRoutes) QuizzesMobile(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// QuizzesWeb provides a mock function with given fields: apiGroup
func (_m *QuizzesRoutes) QuizzesWeb(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// NewQuizzesRoutes creates a new instance of QuizzesRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuizzesRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuizzesRoutes {
	mock := &QuizzesRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
