// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"

	web "github.com/HarsaEdu/harsa-api/internal/model/web"
)

// SubsPlanService is an autogenerated mock type for the SubsPlanService type
type SubsPlanService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, file, subsPlan
func (_m *SubsPlanService) Create(ctx echo.Context, file *multipart.FileHeader, subsPlan *web.SubsPlanCreateRequest) error {
	ret := _m.Called(ctx, file, subsPlan)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, *multipart.FileHeader, *web.SubsPlanCreateRequest) error); ok {
		r0 = rf(ctx, file, subsPlan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateFromExisting provides a mock function with given fields: ctx, file, request, id
func (_m *SubsPlanService) CreateFromExisting(ctx echo.Context, file *multipart.FileHeader, request *web.SubsPlanUpdateRequest, id uint) error {
	ret := _m.Called(ctx, file, request, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, *multipart.FileHeader, *web.SubsPlanUpdateRequest, uint) error); ok {
		r0 = rf(ctx, file, request, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindById provides a mock function with given fields: id
func (_m *SubsPlanService) FindById(id int) (*web.SubsPlanResposne, error) {
	ret := _m.Called(id)

	var r0 *web.SubsPlanResposne
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*web.SubsPlanResposne, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *web.SubsPlanResposne); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*web.SubsPlanResposne)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: offset, limit, search
func (_m *SubsPlanService) GetAll(offset int, limit int, search string) ([]web.SubsPlanResposne, *web.Pagination, error) {
	ret := _m.Called(offset, limit, search)

	var r0 []web.SubsPlanResposne
	var r1 *web.Pagination
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]web.SubsPlanResposne, *web.Pagination, error)); ok {
		return rf(offset, limit, search)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []web.SubsPlanResposne); ok {
		r0 = rf(offset, limit, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]web.SubsPlanResposne)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) *web.Pagination); ok {
		r1 = rf(offset, limit, search)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*web.Pagination)
		}
	}

	if rf, ok := ret.Get(2).(func(int, int, string) error); ok {
		r2 = rf(offset, limit, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SetStatus provides a mock function with given fields: request, id
func (_m *SubsPlanService) SetStatus(request *web.SubsPlanUpdateStatus, id uint) error {
	ret := _m.Called(request, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(*web.SubsPlanUpdateStatus, uint) error); ok {
		r0 = rf(request, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateImage provides a mock function with given fields: ctx, subsPlan, id
func (_m *SubsPlanService) UpdateImage(ctx echo.Context, subsPlan *web.SubsPlanUpdateImage, id int) error {
	ret := _m.Called(ctx, subsPlan, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, *web.SubsPlanUpdateImage, int) error); ok {
		r0 = rf(ctx, subsPlan, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSubsPlanService creates a new instance of SubsPlanService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubsPlanService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubsPlanService {
	mock := &SubsPlanService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
