// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// CategoryRoutes is an autogenerated mock type for the CategoryRoutes type
type CategoryRoutes struct {
	mock.Mock
}

// CategoryMobile provides a mock function with given fields: apiGroup
func (_m *CategoryRoutes) CategoryMobile(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// CategoryWeb provides a mock function with given fields: apiGroup
func (_m *CategoryRoutes) CategoryWeb(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// NewCategoryRoutes creates a new instance of CategoryRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryRoutes {
	mock := &CategoryRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
