// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ChatbotRoutes is an autogenerated mock type for the ChatbotRoutes type
type ChatbotRoutes struct {
	mock.Mock
}

// ChatbotMobile provides a mock function with given fields: apiGroup
func (_m *ChatbotRoutes) ChatbotMobile(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// NewChatbotRoutes creates a new instance of ChatbotRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChatbotRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChatbotRoutes {
	mock := &ChatbotRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
