// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// CourseTrackingRoutes is an autogenerated mock type for the CourseTrackingRoutes type
type CourseTrackingRoutes struct {
	mock.Mock
}

// CourseTrackingMobile provides a mock function with given fields: apiGroup
func (_m *CourseTrackingRoutes) CourseTrackingMobile(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// CourseTrackingWeb provides a mock function with given fields: apiGroup
func (_m *CourseTrackingRoutes) CourseTrackingWeb(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// NewCourseTrackingRoutes creates a new instance of CourseTrackingRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseTrackingRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseTrackingRoutes {
	mock := &CourseTrackingRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
