// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/HarsaEdu/harsa-api/internal/model/domain"
	mock "github.com/stretchr/testify/mock"
)

// FaqRepository is an autogenerated mock type for the FaqRepository type
type FaqRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: Faq
func (_m *FaqRepository) Create(Faq *domain.Faqs) error {
	ret := _m.Called(Faq)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Faqs) error); ok {
		r0 = rf(Faq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *FaqRepository) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindById provides a mock function with given fields: id
func (_m *FaqRepository) FindById(id int) (*domain.Faqs, error) {
	ret := _m.Called(id)

	var r0 *domain.Faqs
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Faqs, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Faqs); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Faqs)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: offset, limit, search
func (_m *FaqRepository) GetAll(offset int, limit int, search string) ([]domain.Faqs, int64, error) {
	ret := _m.Called(offset, limit, search)

	var r0 []domain.Faqs
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]domain.Faqs, int64, error)); ok {
		return rf(offset, limit, search)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []domain.Faqs); ok {
		r0 = rf(offset, limit, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Faqs)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) int64); ok {
		r1 = rf(offset, limit, search)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, string) error); ok {
		r2 = rf(offset, limit, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: Faq, id
func (_m *FaqRepository) Update(Faq *domain.Faqs, id int) error {
	ret := _m.Called(Faq, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Faqs, int) error); ok {
		r0 = rf(Faq, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFaqRepository creates a new instance of FaqRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFaqRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FaqRepository {
	mock := &FaqRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
