// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	web "github.com/HarsaEdu/harsa-api/internal/model/web"
)

// HistorySubModuleService is an autogenerated mock type for the HistorySubModuleService type
type HistorySubModuleService struct {
	mock.Mock
}

// CreateHistorySubModule provides a mock function with given fields: request, userID
func (_m *HistorySubModuleService) CreateHistorySubModule(request *web.CreateHistorySubModuleRequest, userID uint) error {
	ret := _m.Called(request, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(*web.CreateHistorySubModuleRequest, uint) error); ok {
		r0 = rf(request, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewHistorySubModuleService creates a new instance of HistorySubModuleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHistorySubModuleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HistorySubModuleService {
	mock := &HistorySubModuleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
