// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ModuleRoutes is an autogenerated mock type for the ModuleRoutes type
type ModuleRoutes struct {
	mock.Mock
}

// ModuleMobile provides a mock function with given fields: coursesGruop
func (_m *ModuleRoutes) ModuleMobile(coursesGruop *echo.Group) {
	_m.Called(coursesGruop)
}

// ModuleWeb provides a mock function with given fields: coursesGruop
func (_m *ModuleRoutes) ModuleWeb(coursesGruop *echo.Group) {
	_m.Called(coursesGruop)
}

// NewModuleRoutes creates a new instance of ModuleRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModuleRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModuleRoutes {
	mock := &ModuleRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
