// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OptionsService is an autogenerated mock type for the OptionsService type
type OptionsService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: userId, optionId, role
func (_m *OptionsService) Delete(userId uint, optionId uint, role string) error {
	ret := _m.Called(userId, optionId, role)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint, string) error); ok {
		r0 = rf(userId, optionId, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOptionsService creates a new instance of OptionsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOptionsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OptionsService {
	mock := &OptionsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
