// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// PaymentRoutes is an autogenerated mock type for the PaymentRoutes type
type PaymentRoutes struct {
	mock.Mock
}

// PaymentMobile provides a mock function with given fields: apiGroup
func (_m *PaymentRoutes) PaymentMobile(apiGroup *echo.Group) *echo.Group {
	ret := _m.Called(apiGroup)

	var r0 *echo.Group
	if rf, ok := ret.Get(0).(func(*echo.Group) *echo.Group); ok {
		r0 = rf(apiGroup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*echo.Group)
		}
	}

	return r0
}

// PaymentSubscriptionsMobile provides a mock function with given fields: apiGroup
func (_m *PaymentRoutes) PaymentSubscriptionsMobile(apiGroup *echo.Group) *echo.Group {
	ret := _m.Called(apiGroup)

	var r0 *echo.Group
	if rf, ok := ret.Get(0).(func(*echo.Group) *echo.Group); ok {
		r0 = rf(apiGroup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*echo.Group)
		}
	}

	return r0
}

// PaymentWeb provides a mock function with given fields: apiGroup
func (_m *PaymentRoutes) PaymentWeb(apiGroup *echo.Group) *echo.Group {
	ret := _m.Called(apiGroup)

	var r0 *echo.Group
	if rf, ok := ret.Get(0).(func(*echo.Group) *echo.Group); ok {
		r0 = rf(apiGroup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*echo.Group)
		}
	}

	return r0
}

// NewPaymentRoutes creates a new instance of PaymentRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentRoutes {
	mock := &PaymentRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
