// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// QuestionsService is an autogenerated mock type for the QuestionsService type
type QuestionsService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: userId, questionId, role
func (_m *QuestionsService) Delete(userId uint, questionId uint, role string) error {
	ret := _m.Called(userId, questionId, role)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint, string) error); ok {
		r0 = rf(userId, questionId, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQuestionsService creates a new instance of QuestionsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuestionsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuestionsService {
	mock := &QuestionsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
