// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// RecommendationsRoutes is an autogenerated mock type for the RecommendationsRoutes type
type RecommendationsRoutes struct {
	mock.Mock
}

// RecommendationsMobile provides a mock function with given fields: apiGroup
func (_m *RecommendationsRoutes) RecommendationsMobile(apiGroup *echo.Group) *echo.Group {
	ret := _m.Called(apiGroup)

	var r0 *echo.Group
	if rf, ok := ret.Get(0).(func(*echo.Group) *echo.Group); ok {
		r0 = rf(apiGroup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*echo.Group)
		}
	}

	return r0
}

// RecommendationsWeb provides a mock function with given fields: apiGroup
func (_m *RecommendationsRoutes) RecommendationsWeb(apiGroup *echo.Group) *echo.Group {
	ret := _m.Called(apiGroup)

	var r0 *echo.Group
	if rf, ok := ret.Get(0).(func(*echo.Group) *echo.Group); ok {
		r0 = rf(apiGroup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*echo.Group)
		}
	}

	return r0
}

// NewRecommendationsRoutes creates a new instance of RecommendationsRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecommendationsRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecommendationsRoutes {
	mock := &RecommendationsRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
