// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// SubmissionAnswerRoutes is an autogenerated mock type for the SubmissionAnswerRoutes type
type SubmissionAnswerRoutes struct {
	mock.Mock
}

// SubmissionAnswerMobile provides a mock function with given fields: apiGroup
func (_m *SubmissionAnswerRoutes) SubmissionAnswerMobile(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// SubmissionAnswerWeb provides a mock function with given fields: apiGroup
func (_m *SubmissionAnswerRoutes) SubmissionAnswerWeb(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// NewSubmissionAnswerRoutes creates a new instance of SubmissionAnswerRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubmissionAnswerRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubmissionAnswerRoutes {
	mock := &SubmissionAnswerRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
