// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// SubsPlanRoutes is an autogenerated mock type for the SubsPlanRoutes type
type SubsPlanRoutes struct {
	mock.Mock
}

// SubsPlanMobile provides a mock function with given fields: apiGroup
func (_m *SubsPlanRoutes) SubsPlanMobile(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// SubsPlanWeb provides a mock function with given fields: apiGroup
func (_m *SubsPlanRoutes) SubsPlanWeb(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// NewSubsPlanRoutes creates a new instance of SubsPlanRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubsPlanRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubsPlanRoutes {
	mock := &SubsPlanRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
