// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// UserRoutes is an autogenerated mock type for the UserRoutes type
type UserRoutes struct {
	mock.Mock
}

// UserMobile provides a mock function with given fields: apiGroup
func (_m *UserRoutes) UserMobile(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// UserWeb provides a mock function with given fields: apiGroup
func (_m *UserRoutes) UserWeb(apiGroup *echo.Group) {
	_m.Called(apiGroup)
}

// NewUserRoutes creates a new instance of UserRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRoutes {
	mock := &UserRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
